Resources:
  # resource's name
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # this will be from custom.tableName block in serverless.yml
      TableName: ${self:custom.tableName}
      # attributes columns in table
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: noteId
          AttributeType: S
      # define key, primaryId or compositeId
      # Hash or Hash + Range
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: noteId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
